import mujoco 
import yaml 
from tampanda.controllers.position_controller import PositionController
from scipy.spatial.transform import Rotation 
from pathlib import Path
import numpy as np


"""
Classes/Functions/Code in this module have been fully or partially generated by a LLM.
This was necessary, as the WorkBenchMark and LegoSim Environment had some discrepancies.
E.g., a lack of inverse kinematics, different coordinate systems for benchmarking and missing interface etc.
This was too difficult for me to solve, as I have no background in inverse kinematics and such. 
If LLM generated code is not allowed, please ignore this code during the grading process.
"""


# Convergence thresholds of the inverse kinematics.
# The previous 2 mm / 0.02 rad let every solved pose be off by up to 2 mm. That
# is harmless for centre-aligned stacks but too coarse for a brick that rests on
# only half of its support, where 2 mm decide whether it stays or tips over.
IK_POS_TOL = 0.0002
IK_ROT_TOL = 0.002
IK_MAX_ITER = 500

# Simulation steps spent on every waypoint of a motion (one step = 0.04 s).
STEPS_PER_WAYPOINT = 10

# Height above the seat at which the pose of the held brick is measured and
# corrected a second time. 8 mm keeps the brick clear of the 4 mm studs while
# it is shifted sideways.
FINE_CORRECTION_HEIGHT = 0.008

# Centre of the assembly area in the WorkBenchMark YAML files (pos[1] of every
# structure is given around this value; lego_sim expects it around zero).
WORKBENCHMARK_ASSEMBLY_Y = 0.148


class LegoIK:
    def __init__(self, model, data):
        self.model = model
        self.data = data

        self.hand_id = mujoco.mj_name2id(
            model,
            mujoco.mjtObj.mjOBJ_BODY,
            "hand",
        )

    def update_configuration(self, q):
        self.data.qpos[:7] = q
        mujoco.mj_forward(self.model, self.data)

    def solve(self, target_pos, target_quat=None):

        q_original = self.data.qpos[:7].copy()
        q = q_original.copy()

        position_only = target_quat is None

        if position_only:
            mujoco.mj_forward(
                self.model,
                self.data,
            )

            target_quat = self.data.xquat[
                self.hand_id
            ].copy()

        q = np.clip(
            q,
            self.model.jnt_range[:7, 0],
            self.model.jnt_range[:7, 1],
        )

        for _ in range(IK_MAX_ITER):

            self.data.qpos[:7] = q

            mujoco.mj_forward(
                self.model,
                self.data,
            )

            current_pos = self.data.xpos[
                self.hand_id
            ].copy()

            current_rot = self.data.xmat[
                self.hand_id
            ].reshape(3, 3)

            pos_error = (
                target_pos - current_pos
            )

            target_rot = np.zeros(9)

            mujoco.mju_quat2Mat(
                target_rot,
                target_quat,
            )

            target_rot = target_rot.reshape(
                3, 3
            )

            rot_error_mat = (
                target_rot @ current_rot.T
            )

            rot_error = np.array([
                rot_error_mat[2, 1]
                - rot_error_mat[1, 2],

                rot_error_mat[0, 2]
                - rot_error_mat[2, 0],

                rot_error_mat[1, 0]
                - rot_error_mat[0, 1],
            ]) * 0.5

            if position_only:

                if np.linalg.norm(
                    pos_error
                ) < IK_POS_TOL:

                    result = q.copy()

                    self.data.qpos[:7] = q_original

                    mujoco.mj_forward(
                        self.model,
                        self.data,
                    )

                    return result

            else:

                if (
                    np.linalg.norm(pos_error) < IK_POS_TOL
                    and
                    np.linalg.norm(rot_error) < IK_ROT_TOL
                ):

                    result = q.copy()

                    self.data.qpos[:7] = q_original

                    mujoco.mj_forward(
                        self.model,
                        self.data,
                    )

                    return result

            jac_pos = np.zeros(
                (3, self.model.nv)
            )

            jac_rot = np.zeros(
                (3, self.model.nv)
            )

            mujoco.mj_jacBody(
                self.model,
                self.data,
                jac_pos,
                jac_rot,
                self.hand_id,
            )

            J_pos = jac_pos[:, :7]
            J_rot = jac_rot[:, :7]

            if position_only:

                J = J_pos
                error = pos_error

            else:

                J = np.vstack([
                    J_pos,
                    J_rot,
                ])

                error = np.concatenate([
                    pos_error,
                    rot_error,
                ])

            dq = np.linalg.pinv(J) @ error

            q += 0.3 * dq

            q = np.clip(
                q,
                self.model.jnt_range[:7, 0],
                self.model.jnt_range[:7, 1],
            )

        self.data.qpos[:7] = q_original

        mujoco.mj_forward(
            self.model,
            self.data,
        )

        return None



class LegoTampanda:
    def __init__(self, lego):
        self.lego = lego
        self.model = lego.model
        self.data = lego.data

    def get_model(self):
        return self.model

    def get_data(self):
        return self.data

    def get_ik(self):
        return LegoIK(self.model, self.data)

    def get_joint_positions(self):
        return self.data.qpos[:7].copy()

    def set_joint_positions(self, q):
        self.data.qpos[:7] = q
        mujoco.mj_forward(self.model, self.data)

    def is_collision_free(self, q):
        return True




def convert_workbenchmark_yaml(input_yaml, output_yaml):
    with open(input_yaml, "r") as f:
        task = yaml.safe_load(f)

    blocks = []

    for block in task["blocks"]:
        p = block["pos"]
        r = block.get("rotation", [0, 0, 0])

        blocks.append({
            "id": block["name"],
            "type": block["type"],
            "color": block["color"],
            "target": {
                "position": [
                    float(p[0]),
                    float(p[1]) - WORKBENCHMARK_ASSEMBLY_Y,
                    float(p[2]),
                ],
                "yaw_deg": float(r[2]),
            },
        })

    converted = {
        "schema_version": 1,
        "product": {
            "name": Path(input_yaml).stem,
        },
        "blocks": blocks,
    }

    with open(output_yaml, "w") as f:
        yaml.safe_dump(
            converted,
            f,
            sort_keys=False,
        )


def move_linear(env, q_goal, steps=50):
    q_start = env.data.qpos[:7].copy()

    distance = np.linalg.norm(q_goal - q_start)

    if distance < 1e-9:
        # The arm is already there. Interpolating a zero-length segment would
        # divide by zero and crash with "cannot convert float NaN to integer".
        path = [np.asarray(q_goal, dtype=float)]
    else:
        path = PositionController.interpolate_linear_points(
            q_start,
            q_goal,
            step_size=distance / steps,
        )

    for q in path:
        action = env.data.ctrl.copy()
        action[:7] = q

        for _ in range(STEPS_PER_WAYPOINT):
            env.step(action)


def move_vertical(env, start_pos, target_pos, quat, tampanda, steps=50):
    """Follow a straight Cartesian line. Returns False if the end pose was unreachable."""
    reached = True

    for pos in np.linspace(start_pos, target_pos, steps):
        q = tampanda.get_ik().solve(pos, quat)

        action = env.data.ctrl.copy()
        # Without a solution keep the previous joint command instead of writing
        # None into the control vector.
        reached = q is not None
        if reached:
            action[:7] = q

        for _ in range(STEPS_PER_WAYPOINT):
            env.step(action)

    return reached


def get_brick_and_hand_pose(env, env_name):
    brick = env.data.body(env_name)
    hand = env.data.body("hand")

    return (
        brick.xpos.copy(),
        brick.xquat.copy(),
        hand.xpos.copy(),
        hand.xquat.copy(),
    )


def get_place_target(env, item_pddl):
    parts = item_pddl.split("_")

    benchmark_id = "_".join(
        parts[2:] + parts[:2]
    )

    target = next(
        (
            t
            for t in env.episode_manifest["target_blocks"]
            if t["id"] == benchmark_id
        ),
        None,
    )

    if target is None:
        print(
            "PLACE: No target found for",
            item_pddl,
            "->",
            benchmark_id,
            flush=True,
        )
        return None, None

    target_pos = np.array(
        target["position"],
        dtype=float,
    )

    target_rot = Rotation.from_euler(
        "z",
        target["yaw_rad"],
    )

    return target_pos, target_rot



def get_stack_target(
    env,
    item,
    support,
    name_mapping,
):
    def to_benchmark_id(name):
        parts = name.split("_")
        return "_".join(
            parts[2:] + parts[:2]
        )

    # ------------------------------------------------------------
    # Benchmark IDs
    # ------------------------------------------------------------

    item_benchmark_id = to_benchmark_id(item)
    support_benchmark_id = to_benchmark_id(support)

    # ------------------------------------------------------------
    # Find benchmark targets
    # ------------------------------------------------------------

    item_target = next(
        (
            t
            for t in env.episode_manifest["target_blocks"]
            if t["id"] == item_benchmark_id
        ),
        None,
    )

    support_target = next(
        (
            t
            for t in env.episode_manifest["target_blocks"]
            if t["id"] == support_benchmark_id
        ),
        None,
    )

    if item_target is None:
        print(
            "STACK: No target found for",
            item,
            "->",
            item_benchmark_id,
            flush=True,
        )
        return None, None

    if support_target is None:
        print(
            "STACK: No target found for support",
            support,
            "->",
            support_benchmark_id,
            flush=True,
        )
        return None, None

    # ------------------------------------------------------------
    # Benchmark poses
    # ------------------------------------------------------------

    item_target_pos = np.array(
        item_target["position"],
        dtype=float,
    )

    item_target_rot = Rotation.from_euler(
        "z",
        item_target["yaw_rad"],
    )

    support_target_pos = np.array(
        support_target["position"],
        dtype=float,
    )

    support_target_rot = Rotation.from_euler(
        "z",
        support_target["yaw_rad"],
    )

    # ------------------------------------------------------------
    # Actual support pose in MuJoCo
    # ------------------------------------------------------------

    support_body = name_mapping[support]

    actual_support_pos = (
        env.data.body(support_body).xpos.copy()
    )

    actual_support_quat = (
        env.data.body(support_body).xquat.copy()
    )

    actual_support_rot = Rotation.from_quat(
        actual_support_quat[[1, 2, 3, 0]]
    )

    # ------------------------------------------------------------
    # Apply benchmark relation to actual support
    # ------------------------------------------------------------

    # A brick is indistinguishable from itself after a turn by its yaw symmetry
    # (2x2: 90 deg, 4x2: 180 deg), and place_at() may use such an equivalent
    # orientation. Only the support's residual misalignment, folded into that
    # symmetry range, may be carried over to the item. Applying the full actual
    # rotation would turn the item's offset by the same half or quarter turn and
    # put it on the wrong side of the support.
    support_symmetry = np.pi / 2 if support.endswith("2x2") else np.pi

    yaw_error = (
        actual_support_rot
        * support_target_rot.inv()
    ).as_euler("zyx")[0]

    yaw_error = (
        (yaw_error + support_symmetry / 2) % support_symmetry
        - support_symmetry / 2
    )

    residual_rot = Rotation.from_euler("z", yaw_error)

    target_pos = (
        actual_support_pos
        + residual_rot.apply(
            item_target_pos - support_target_pos
        )
    )

    target_rot = (
        residual_rot
        * item_target_rot
    )

    return target_pos, target_rot



def place_at(
    env,
    item,
    target_pos,
    target_rot,
    name_mapping,
    tampanda,
    HOME_Q,
    approach_offset,
    open_gripper,
    held_relative_pos,
    held_relative_rot,
    unload=0.0,
):
    """
    Places the held brick at target_pos / target_rot and releases it.

    unload: distance (m) by which target_pos lies below the seat of the brick,
    i.e. how far the arm presses it down. The hand backs off by this distance
    before the gripper opens.
    """
    env_name = name_mapping[item]

    relative_pos = held_relative_pos[item]
    relative_rot = held_relative_rot[item]

    # ---------------------------------------------------------
    # APPROACH
    # ---------------------------------------------------------

    # The requested orientation and its symmetry-equivalent twins (2x2: every
    # 90 deg, 4x2: every 180 deg) describe the same placed brick and are scored
    # identically by the benchmark. Among the reachable ones the arm takes the
    # one with the shortest joint-space path. Besides being faster this keeps
    # the wrist rotation small: the brick lags ~3 % behind every wrist turn and
    # wedges itself between the fingers, so a 150 deg turn where 30 deg would
    # do leaves it twisted by several degrees when it is released.
    symmetry_deg = 90.0 if item.endswith("2x2") else 180.0
    requested_rot = target_rot
    q_current = env.data.qpos[:7].copy()
    q_approach = None

    for k in range(int(round(360.0 / symmetry_deg))):
        candidate_rot = requested_rot * Rotation.from_euler(
            "z",
            k * symmetry_deg,
            degrees=True,
        )

        candidate_hand_pos = (
            target_pos
            + candidate_rot.apply(relative_pos)
        )

        candidate_hand_rot = (
            candidate_rot * relative_rot
        )

        q_candidate = tampanda.get_ik().solve(
            candidate_hand_pos + approach_offset,
            candidate_hand_rot.as_quat()[[3, 0, 1, 2]],
        )

        if q_candidate is None:
            continue

        if (
            q_approach is None
            or np.linalg.norm(q_candidate - q_current)
            < np.linalg.norm(q_approach - q_current)
        ):
            q_approach = q_candidate
            target_rot = candidate_rot

    if q_approach is None:
        print("PLACE: approach IK failed", flush=True)
        return False

    move_linear(
        env,
        q_approach,
    )

    # ---------------------------------------------------------
    # MEASURE ACTUAL HAND / BRICK RELATION
    # ---------------------------------------------------------

    (
        brick_pos,
        brick_quat,
        hand_pos,
        hand_quat,
    ) = get_brick_and_hand_pose(
        env,
        env_name,
    )

    brick_rot = Rotation.from_quat(
        brick_quat[[1, 2, 3, 0]]
    )

    hand_rot = Rotation.from_quat(
        hand_quat[[1, 2, 3, 0]]
    )

    actual_relative_pos = (
        brick_rot.inv().apply(
            hand_pos - brick_pos
        )
    )

    actual_relative_rot = (
        brick_rot.inv()
        * hand_rot
    )

    # ---------------------------------------------------------
    # CORRECTED APPROACH
    # ---------------------------------------------------------

    desired_brick_pos = (
        target_pos
        + approach_offset
    )

    corrected_hand_pos = (
        desired_brick_pos
        + target_rot.apply(actual_relative_pos)
    )

    corrected_hand_rot = (
        target_rot
        * actual_relative_rot
    )

    corrected_hand_quat = (
        corrected_hand_rot.as_quat()[[3, 0, 1, 2]]
    )

    q_correct = tampanda.get_ik().solve(
        corrected_hand_pos,
        corrected_hand_quat,
    )

    if q_correct is None:
        print("PLACE: correction IK failed", flush=True)
        return False

    move_linear(
        env,
        q_correct,
    )

    # ---------------------------------------------------------
    # LOWER TO JUST ABOVE THE SEAT AND CORRECT AGAIN
    # ---------------------------------------------------------

    final_hand_pos = (
        target_pos
        + target_rot.apply(actual_relative_pos)
    )

    above_seat = np.array([0.0, 0.0, FINE_CORRECTION_HEIGHT])

    lowered = move_vertical(
        env,
        corrected_hand_pos,
        final_hand_pos + above_seat,
        corrected_hand_quat,
        tampanda,
    )

    # The correction above was measured 15 cm over the target. On the way down
    # the brick shifts in the grasp by 1 to 2 mm, which is as much as the
    # stability bias of a half-supported brick. Measure its horizontal error
    # once more and move the hand by that amount before the last millimetres.
    fine_correction = np.zeros(3)

    if FINE_CORRECTION_HEIGHT > 0.0:
        brick_pos = env.data.body(env_name).xpos.copy()
        fine_correction[:2] = target_pos[:2] - brick_pos[:2]

        move_vertical(
            env,
            final_hand_pos + above_seat,
            final_hand_pos + above_seat + fine_correction,
            corrected_hand_quat,
            tampanda,
            steps=5,
        )

    final_hand_pos = final_hand_pos + fine_correction

    # ---------------------------------------------------------
    # LOWER TO FINAL TARGET
    # ---------------------------------------------------------

    lowered = move_vertical(
        env,
        final_hand_pos + above_seat,
        final_hand_pos,
        corrected_hand_quat,
        tampanda,
        steps=10,
    ) and lowered

    # ---------------------------------------------------------
    # UNLOAD
    # ---------------------------------------------------------

    # At the end of the descent the position-controlled arm presses the brick
    # onto its seat (43 N for 1 mm in our measurements). Opening the gripper
    # under that load releases it at once. A brick that rests on only half of
    # its support then rocks by several degrees and may tip over; whether it
    # does depends on details as small as the initial layout of the bricks.
    # Backing off first lets the brick rest under its own weight.
    if unload > 0.0:
        move_vertical(
            env,
            final_hand_pos,
            final_hand_pos + np.array([0.0, 0.0, unload]),
            corrected_hand_quat,
            tampanda,
            steps=5,
        )

    # ---------------------------------------------------------
    # RELEASE
    # ---------------------------------------------------------

    open_gripper(env)

    # ---------------------------------------------------------
    # RETREAT
    # ---------------------------------------------------------

    actual_hand_pos = (
        env.data.body("hand").xpos.copy()
    )

    retreat_target = (
        actual_hand_pos
        + approach_offset
    )

    move_vertical(
        env,
        actual_hand_pos,
        retreat_target,
        corrected_hand_quat,
        tampanda,
    )

    # ---------------------------------------------------------
    # HOME
    # ---------------------------------------------------------

    move_linear(
        env,
        HOME_Q,
    )

    if not lowered:
        print("PLACE: target pose not reachable", flush=True)

    return lowered
